services:
    _defaults:
        public: true

    coreshop.payum.mollie.action.capture: '@CoreShop\Payum\MollieBundle\Action\CaptureAction'
    CoreShop\Payum\MollieBundle\Action\CaptureAction:
        tags:
            - { name: payum.action, factory: mollie, alias: payum.action.capture }

    coreshop.payum.mollie.action.cancel: '@CoreShop\Payum\MollieBundle\Action\CancelAction'
    CoreShop\Payum\MollieBundle\Action\CancelAction:
        tags:
            - { name: payum.action, factory: mollie, alias: payum.action.cancel }

    coreshop.payum.mollie.action.convert_payment: '@CoreShop\Payum\MollieBundle\Action\ConvertPaymentAction'
    CoreShop\Payum\MollieBundle\Action\ConvertPaymentAction:
        tags:
            - { name: payum.action, factory: mollie, alias: payum.action.convert_payment }

    coreshop.payum.mollie.action.notify: '@CoreShop\Payum\MollieBundle\Action\NotifyAction'
    CoreShop\Payum\MollieBundle\Action\NotifyAction:
        tags:
            - { name: payum.action, factory: mollie, alias: payum.action.notify }

    coreshop.payum.mollie.action.status: '@CoreShop\Payum\MollieBundle\Action\StatusAction'
    CoreShop\Payum\MollieBundle\Action\StatusAction:
        tags:
            - { name: payum.action, factory: mollie, alias: payum.action.status }

    coreshop.payum.mollie.action.api.refund_order: '@CoreShop\Payum\MollieBundle\Action\Api\RefundOrderAction'
    CoreShop\Payum\MollieBundle\Action\Api\RefundOrderAction:
        tags:
            - { name: payum.action, factory: mollie, alias: payum.action.api.refund_order }

    coreshop.payum.mollie.action.api.refund_order_lines: '@CoreShop\Payum\MollieBundle\Action\Api\RefundOrderLinesAction'
    CoreShop\Payum\MollieBundle\Action\Api\RefundOrderLinesAction:
        tags:
            - { name: payum.action, factory: mollie, alias: payum.action.api.refund_order_lines }

    coreshop.payum.mollie.action.api.create_shipment: '@CoreShop\Payum\MollieBundle\Action\Api\CreateShipmentAction'
    CoreShop\Payum\MollieBundle\Action\Api\CreateShipmentAction:
        tags:
            - { name: payum.action, factory: mollie, alias: payum.action.api.create_shipment }

    coreshop.payum.mollie.action.api.ship_all: '@CoreShop\Payum\MollieBundle\Action\Api\ShipAllAction'
    CoreShop\Payum\MollieBundle\Action\Api\ShipAllAction:
        tags:
            - { name: payum.action, factory: mollie, alias: payum.action.api.ship_all }
