services:
    _defaults:
        public: true
        autowire: true

    CoreShop\Payum\MollieBundle\Extension\ConvertOrderExtension:
        arguments:
            - '%coreshop.currency.decimal_factor%'
        tags:
            - { name: payum.extension, alias: mollie_order_extension, factory: mollie, gateway: mollie, prepend: false }

    CoreShop\Payum\MollieBundle\Extension\ConvertOrderItemsExtension:
        arguments:
            - '%coreshop.currency.decimal_factor%'
            - '%coreshop.currency.decimal_precision%'
        tags:
            - { name: payum.extension, alias: mollie_order_items_extension, factory: mollie, gateway: mollie, prepend: false }

    CoreShop\Payum\MollieBundle\Extension\ConvertOrderAddressesExtension:
        tags:
            - { name: payum.extension, alias: mollie_order_addresses_extension, factory: mollie, gateway: mollie, prepend: false }
