services:
    _defaults:
        public: true

    CoreShop\Payum\MollieBundle\Extension\ConvertOrderExtension:
        arguments:
            - '%coreshop.currency.decimal_factor%'
        tags:
            - { name: payum.extension, alias: mollie_order_extension, factory: mollie, gateway: mollie, prepend: false }

    CoreShop\Payum\MollieBundle\Extension\ConvertOrderItemsExtension:
        arguments:
            - '@CoreShop\Component\Pimcore\Templating\Helper\LinkGeneratorHelper'
            - '%coreshop.currency.decimal_factor%'
        tags:
            - { name: payum.extension, alias: mollie_order_items_extension, factory: mollie, gateway: mollie, prepend: false }

    CoreShop\Payum\MollieBundle\Extension\ConvertOrderAddressesExtension:
        arguments:
            - '@libphonenumber.phone_number_util'
        tags:
            - { name: payum.extension, alias: mollie_order_addresses_extension, factory: mollie, gateway: mollie, prepend: false }
