services:
    _defaults:
        public: true
        autoconfigure: true
        autowire: true
        tags:
            - { name: 'kernel.event_subscriber' }

    CoreShop\Payum\MollieBundle\EventListener\OrderListener: ~

    CoreShop\Payum\MollieBundle\EventListener\OrderShipmentListener: ~