services:
    _defaults:
        public: true

    CoreShop\Payum\MollieBundle\EventListener\CreditMemoListener:
        arguments:
            - '@coreshop.payum.mollie.factory.refund_order_lines'
            - '@coreshop.repository.payment'
            - '@payum'
            - '@coreshop.factory.payum_get_status'
            - '%coreshop.currency.decimal_factor%'
        tags:
            - { name: kernel.event_subscriber }
