services:
    _defaults:
        public: true

    coreshop.payum.mollie.factory.refund_order: '@CoreShop\Payum\MollieBundle\Factory\RefundOrderFactory'
    CoreShop\Payum\MollieBundle\Factory\RefundOrderFactoryInterface: '@CoreShop\Payum\MollieBundle\Factory\RefundOrderFactory'
    CoreShop\Payum\MollieBundle\Factory\RefundOrderFactory:

    coreshop.payum.mollie.factory.refund_order_lines: '@CoreShop\Payum\MollieBundle\Factory\RefundOrderLinesFactory'
    CoreShop\Payum\MollieBundle\Factory\RefundOrderLinesFactoryInterface: '@CoreShop\Payum\MollieBundle\Factory\RefundOrderLinesFactory'
    CoreShop\Payum\MollieBundle\Factory\RefundOrderLinesFactory:

    coreshop.payum.mollie.factory.create_shipment: '@CoreShop\Payum\MollieBundle\Factory\CreateShipmentFactory'
    CoreShop\Payum\MollieBundle\Factory\CreateShipmentFactoryInterface: '@CoreShop\Payum\MollieBundle\Factory\CreateShipmentFactory'
    CoreShop\Payum\MollieBundle\Factory\CreateShipmentFactory:

    coreshop.payum.mollie.factory.ship_all: '@CoreShop\Payum\MollieBundle\Factory\ShipAllFactory'
    CoreShop\Payum\MollieBundle\Factory\ShipAllFactoryInterface: '@CoreShop\Payum\MollieBundle\Factory\ShipAllFactory'
    CoreShop\Payum\MollieBundle\Factory\ShipAllFactory:

