imports:
    - { resource: services/actions.yml }
    - { resource: services/extensions.yml }
    - { resource: services/requests.yml }

services:
    _defaults:
        public: true

    CoreShop\Payum\MollieBundle\Form\Payment\MollieType:
        tags:
            - { name: coreshop.gateway_configuration_type, type: mollie }
            - { name: form.type }

    payum.mollie_gateway_factory:
        class: Payum\Core\Bridge\Symfony\Builder\GatewayFactoryBuilder
        arguments:
            - 'CoreShop\Payum\MollieBundle\MollieGatewayFactory'
        tags:
            - { name: payum.gateway_factory_builder, factory: mollie }



